# Generated by Django 5.1.2 on 2024-12-01 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='video-lessons/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='sana')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lessons', verbose_name='dars')),
            ],
            options={
                'verbose_name': 'Video dars',
                'verbose_name_plural': 'Video darslar',
            },
        ),
    ]
