# Generated by Django 5.1.2 on 2024-12-01 07:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ratelesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratelesson',
            unique_together={('user', 'lesson')},
        ),
    ]
